### ISSUE TITLE
Ability to get all labels

### ISSUE THREAD

**Issue by Uinelj** [messense/fasttext-rs#10]
Hello,

I've been wondering if it could be possible to get the same functionnality as the `labels` method/property on the python wrapper. I see that you rely on `cfasttext`, and I haven't found anything that could replicate this feature. I'd be glad to try to add this in Rust, but I don't know if I'd have to touch the underlying C wrapper.

**Comment by messense** [comment]
Added in [v0.7.2](https://crates.io/crates/fasttext/0.7.2).
