### ISSUE TITLE
cfasttext-sys on crates.io missing gcc 13 fix.

### ISSUE THREAD

**Issue by 0e4ef622** [messense/fasttext-rs#21]
The `#include <stdint.h>` isn't present.
https://docs.rs/crate/cfasttext-sys/0.7.7/source/cfasttext/fasttext/src/args.cc

**Comment by messense** [comment]
Fixed in v0.7.8: https://docs.rs/crate/cfasttext-sys/0.7.8/source/cfasttext/fasttext/src/args.cc
