### ISSUE TITLE
Program panics if any null byte is encountered.

### ISSUE THREAD

**Issue by Uinelj** [messense/fasttext-rs#6]
When using prediction functions with strings containing a null byte, the library crashes due to an `unwrap()` on a `CString` creation.
However, encountering null bytes happens in the nature and while the presence of null bytes could be checked upstream, I don't think that having the program crash is intended behaviour.

This could be fixed by removing `unwrap`, change return types if applicable and map the error to a String.

I'd be glad to implement such a fix :)

**Comment by messense** [comment]
Thanks for reporting, go ahead fix it I'm happy to accept a PR.

**Comment by messense** [comment]
BTW, I think maybe we should use the [c_fixed_string](https://docs.rs/c_fixed_string/0.2.0/c_fixed_string/) crate instead of just `CString`.
