### ISSUE TITLE
FastText struct shouldn't implement clone

### ISSUE THREAD

**Issue by caio** [messense/fasttext-rs#9]
Hello,

First of all, thanks a lot for your work on this crate!

Cloning doesn't play well with the custom drop logic, it's better to remove the `Clone` bit from derive and let users share it via Arc/Rc I think, otherwise this can easily happen:

```rust
use fasttext::FastText;

fn main() {
    let mut ft = FastText::new();
    ft.load_model("cooking.model.bin").unwrap();

    let cloned = ft.clone();
    drop(cloned);

    // boom!
    ft.is_quant();
}
```

Running it causes a `'cargo run' terminated by signal SIGSEGV (Address boundary error)`

**Comment by messense** [comment]
Thanks for reporting.
